2018-09-05 16:46:48,488 - DataBase.py[line:23] - INFO: database class is creating...
2018-09-05 16:46:58,499 - DataBase.py[line:49] - ERROR: connect database failed, (2003, "Can't connect to MySQL server on '192.168.43.14' (timed out)")
2018-09-05 16:46:58,499 - DataBase.py[line:51] - INFO: database is connecting...
